### ISSUE TITLE
Error building vignettes

### ISSUE THREAD

**Issue by keesvanbochove** [rekkasa/EmpiricalCalibration#11]
When building the package using `devtools::build()`, I get the following error:

```
E  creating vignettes (11.4s)
   --- re-building 'EmpiricalCiCalibrationVignette.Rmd' using rmarkdown
   Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
   Error: processing vignette 'EmpiricalCiCalibrationVignette.Rmd' failed with diagnostics:
   The 'markdown' package should be installed and declared as a dependency of the 'EmpiricalCalibration' package (e.g., in 
the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
   --- failed re-building 'EmpiricalCiCalibrationVignette.Rmd'
```
However I have installed both `knitr` and `rmarkdown`, and the vignettes folder only contains `.Rmd` files. It seems that any of the following actions fix this problem:
* Adding `markdown` to suggested packages (as the linked issue suggests)
* Changing `VignetteBuilder: knitr` to `VignetteBuilder: rmarkdown` in `DESCRIPTION`, but then it is very fast and doesn't actually build the HTML docs

The following doesn't solve it:
* Adding `Roxygen: list(load = "installed", markdown = TRUE)` to `DESCRIPTION`

I think the best way to fix it is just to take the first action listed above, but any insights welcome - the setup is still a bit puzzling to me.

**Comment by rekkasa** [comment]
I couldn't reproduce the error. Could it be that you need to update the version of `pandoc` and `pandoc-citeproc`? Maybe we should ask Marc about it

**Comment by msuchard** [comment]
`markdown` should be added to `Suggests:`
